civico/urls.py
from django.urls import path
from . import views

app_name = 'civico'
urlpatterns = [
    path('', views.index, name='index'),
]

civicodental/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('civico.urls')),
    path('promociones/', include('promociones.urls')),
    path('services/', include('services.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

promociones/urls.py
from django.urls import path
#from . import views
from .views import *

app_name = 'promociones'
urlpatterns = [
    path('', HomeView, name='home'),
    path('article/<int:pk>', ArticleDetailView, name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post' ),
    path('like/<int:pk>', LikeView, name='like_post'),
]

promociones/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

from calltoaction.models import CallToAction as Call2Action
from django.core.exceptions import ValidationError

class Page(models.Model):
    name = models.CharField(max_length=255, default="Promociones")
    description = models.TextField(null=True, blank=True)
    is_enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

def validate_numeric_whatsapp_number(value):
    if not value.isdigit():
        raise ValidationError('WhatsApp number must contain only numeric characters.')


class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/promociones/", default=None)
    title_tag = models.CharField(max_length=255, default="Promociones")
    author = models.ForeignKey(User, related_name='promo_author', on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    snippet = models.CharField(max_length=255, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='promociones_posts_likes')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='articles')
    tags = models.ManyToManyField(Tag, blank=True)
    sort_order = models.IntegerField(default=1)
    is_visible = models.BooleanField(default=True)
    call2action = models.ForeignKey(
        Call2Action,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='promo_call2action',
        )

    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('promociones:home')


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models. DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

promociones/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title',
                  'header_image',
                  'title_tag',
                  'snippet',
                  'body',
                  'category',
                  'tags',
                  'sort_order',
                  'call2action',
                  'is_visible',)

        widgets = {
            'header_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'sort_order': forms.NumberInput(attrs={'class': 'form-control'}),
            'call2action': forms.Select(attrs={'class': 'form-control'}),
            'is_visible': forms.CheckboxInput(attrs={'class': 'form-check-input'}),            
        }

promociones/views.py
import os
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Tag, Page
from sectionselection.models import SectionSelection
from calltoaction.models import CallToAction
from .forms import PostForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
# from django.conf import settings
from django.http import JsonResponse
import random
from random import choice


def HomeView(request):

    template_path_filter = 'promociones/home.html'

    sections = SectionSelection.objects.filter(
        is_visible=True,
        page__template_path=template_path_filter)
    
    posts = Post.objects.filter(is_visible=True).order_by('-post_date')
    
    enabled_calltoaction = CallToAction.objects.filter(is_mainpage_enabled=True)
    calltoaction = choice(enabled_calltoaction) if enabled_calltoaction.exists() else None

    enabled_promo_page_content = Page.objects.filter(is_enabled=True)
    promo_page_random_content = None
    if enabled_promo_page_content.exists():
        promo_page_random_content = random.choice(enabled_promo_page_content)

    context = {
        'sections': sections,
        'promo_posts': posts,
        'calltoaction': calltoaction,
        'promo_page_content': promo_page_random_content,        
    }

    template_name = 'promociones/home.html'

    return render(request, template_name, context)


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    likes_count = post.likes.count()

    # Return JSON response with updated like count
    return JsonResponse({'likes_count': likes_count})


def ArticleDetailView(request, pk):
    template_path_filter = 'promociones/article_details.html'

    sections = SectionSelection.objects.filter(
        is_visible=True,
        page__template_path=template_path_filter)

    post = get_object_or_404(Post, pk=pk)
    posts = Post.objects.filter(is_visible=True).order_by('sort_order')

    calltoaction = None
    if post.call2action:
        calltoaction = get_object_or_404(CallToAction, id=post.call2action.id)

    categories = Category.objects.all()
    category_counts = {category.name: category.articles.count() for category in categories}
    
    tags = Tag.objects.all()

    enabled_promo_page_content = Page.objects.filter(is_enabled=True)    
    promo_page_random_content = None
    if enabled_promo_page_content.exists():
        promo_page_random_content = random.choice(enabled_promo_page_content)

    context = {
        'sections': sections,
        'post': post,
        'promo_posts': posts,
        'calltoaction': calltoaction,
        'category_counts': category_counts,
        'tags': tags,
        'promo_page_content': promo_page_random_content,
    }

    template_name = 'promociones/article_details.html'

    return render(request, template_name, context)


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'promociones/add_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'promociones/update_post.html'

    def form_valid(self, form):
        # Get the existing post object
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
  
        # Check if 'header_image' is in form.changed_data, meaning it's changed
        if 'header_image' in form.changed_data:
            # Check if 'header_image-clear' exists in form.cleaned_data
            if form.cleaned_data.get('header_image-clear'):
                # Clearing the selection, delete the existing image
                if post.header_image:
                    old_image_path = post.header_image.path
                    if os.path.exists(old_image_path):
                        os.remove(old_image_path)
                # Set header_image to None in case the field is not required
                post.header_image = None
            else:
                # A new image was uploaded, delete the old image if it exists
                if post.header_image:
                    old_image_path = post.header_image.path
                    if os.path.exists(old_image_path):
                        os.remove(old_image_path)
        

        # Save the form with commit=True to update the database
        form.save()

        return super().form_valid(form)


class DeletePostView(DeleteView):
    model = Post
    template_name = 'promociones/delete_post.html'
    success_url = reverse_lazy('promociones:home')

promociones/templates/promociones/section/call2action.html
{% load static %}

<!-- Call-to-action Section - Home Page -->
{% if post.calltoaction %}
<section id="{{ section_selection.section.html_id }}" class="call-to-action">

  {% if post.calltoaction.background_image %}
  <img src="{{ post.calltoaction.background_image.url }}" alt="...">
  {% else %}
  <img src="{% static 'civico/img/call2action.jpg' %}" alt="">
  {% endif %}

  <div class="container">
    <div class="row justify-content-center" data-aos="zoom-in" data-aos-delay="100">
      <div class="col-xl-10">
        <div class="text-center">
          <h3>{{ post.calltoaction.title }}</h3>
          <p>{{ post.calltoaction.description }}</p>
            <a href="https://api.whatsapp.com/send?phone={{ post.calltoaction.whatsapp_number }}&text={{ post.calltoaction.whatsapp_message }}"
              class="cta-btn" target="_blank"><i class="bi bi-whatsapp"></i> {{ post.calltoaction.btn_text }}</a>
            <!-- <a class="cta-btn" href="{% url 'civico:index' %}#contact">Agenda tu cita!</a> -->
        </div>
      </div>
    </div>
  </div>

</section>
{% endif %}

<!-- End Call-to-action Section -->

promociones/templates/promociones/section/call2action22.html
{% load static %}

<!-- Call-to-action Section - Home Page -->
{% if promo_calltoaction.all %}
<section id="{{ section_selection.section.html_id }}" class="call-to-action">

  {% if promo_calltoaction.background_image %}
  <img src="{{ promo_calltoaction.background_image.url }}" alt="...">
  {% else %}
  <img src="{% static 'civico/img/call2action.jpg' %}" alt="">
  {% endif %}

  <div class="container">
    <div class="row justify-content-center" data-aos="zoom-in" data-aos-delay="100">
      <div class="col-xl-10">
        <div class="text-center">
          <h3>{{ promo_calltoaction.title }}</h3>
          <p>{{ promo_calltoaction.description }}</p>
            <a href="https://api.whatsapp.com/send?phone={{ promo_calltoaction.whatsapp_number }}&text={{ promo_calltoaction.whatsapp_message }}"
              class="cta-btn" target="_blank"><i class="bi bi-whatsapp"></i> {{ promo_calltoaction.btn_text }}</a>
            <!-- <a class="cta-btn" href="{% url 'civico:index' %}#contact">Agenda tu cita!</a> -->
        </div>
      </div>
    </div>
  </div>

</section>
{% endif %}

<!-- End Call-to-action Section -->

promociones/templates/promociones/section/posts.html
<section id="{{ section_selection.section.html_id }}" class="blog">
    <div class="container section-title" data-aos="fade-up">
        {% if promo_page_content %}
        <a href="{% url 'promociones:home' %}"><h2>{{ promo_page_content.name }}</h2></a>
        <p>{{ promo_page_content.description }}</p>
        {% endif %}
    </div>

    {% if user.is_authenticated and user.is_staff %}
    <div class="container">
        <div class="d-flex justify-content-end align-items-center">
            <a href="{% url 'promociones:add_post' %}"><i class="bi bi-plus-square-fill" style="font-size: 2em"></i></a>
        </div>    
    </div>
    {% endif %}

    {% if promo_posts.all %}
    <div class="container" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 posts-list">

            {% for post in promo_posts %}
            <div class="col-xl-4 col-md-6">
                <article class="article">


                    <div class="post-img">
                        {% if post.header_image %}
                        <a href="{% url 'promociones:article-detail' post.pk %}">
                            <img src="{{ post.header_image.url }}" alt="..." class="img-fluid">
                        </a>
                        {% endif %}
                    </div>
                    

                    <div class="d-flex align-items-center justify-content-between">

                        <p class="post-category">{{ post.category }}</p>
                        {% if user.is_authenticated and user.is_staff %}
                        <div>
                            <small>
                                <a href="{% url 'promociones:update_post' post.pk %}"><i class="bi bi-pencil"></i></a>
                                <a href="{% url 'promociones:delete_post' post.pk %}"><i class="bi bi-trash"></i></a>
                            </small>
                        </div>
                        {% endif %}
                    </div>

                    <h2 class="title">
                        <a href="{% url 'promociones:article-detail' post.pk %}">{{ post.title }}</a>
                    </h2>

                    <p class="post-category">{{ post.snippet }}</p>

                    <div class="d-flex align-items-center justify-content-start">

                        {% if post.author.profile and post.author.profile.profile_pic %}
                        <img src="{{ post.author.profile.profile_pic.url }}" alt="..."
                            class="img-fluid post-author-img flex-shrink-0">
                        {% else %}
                        <i class="bi bi-person" style="font-size: 2rem; margin-right: 10px; color: gray;"></i>
                        {% endif %}

                        <div class="post-meta">
                            <p class="post-author">{{ post.author.first_name }} {{ post.author.last_name }}</p>
                            <p class="post-date">{{ post.post_date }}</p>
                        </div>
                    </div>

                </article>
            </div>

            {% endfor %}

        </div>
    </div>
    {% endif %}
</section>